//
//  TrackingMessage.h
//  TeXtended
//
//  Created by Tobias Mende on 18.06.13.
//  Copyright (c) 2013 Tobias Mende. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Constants.h"


/**
 * This class is a message object for informing the user about latex code issues like warnings, infos, debug messages and errors.
 *
 * Instances of this class are generates by a subclass of the class Parser and might be used in the LineNumberView or any other view to inform the user about code issues.
 *
 * **Author:** Tobias Mende
 */

@interface TrackingMessage : NSObject

/** The path to the latex document for which this message was generated */
@property NSString* document;

/** The line of the issue */
@property NSUInteger line;

/** The column of this issue (might be empty) */
@property NSUInteger column;

/** The type of this issue (see class Constants for further information) */
@property TMTTrackingMessageType type;

/** The title of this issue. Might be a brief explanation of the issue or the parser that generated the message (in most cases only a single line */
@property NSString *title;

/** A longer description of this issue, extracted from any syntax checkers output */
@property NSString *info;

/** An optional longer information generated by some smart TeXtended algorithms (might be empty) */
@property NSString *furtherInfo;

/**
 * The default initializer
 *
 * @param type the message type
 * @param document the path to the latex document
 * @param line the line of the issue
 * @param title the issues title
 * @param info the description of this message
 *
 * @return a new message of the given type
 */
- (id) initMessage:(TMTTrackingMessageType)type inDocument:(NSString *)document inLine:(NSUInteger)line withTitle:(NSString*)title andInfo:(NSString *)info;

/**
 * Generator for a new error message (a message of the type TMTErrorMessage)
 *
 * @param document the path to the latex document
 * @param line the line of the issue
 * @param title the issues title
 * @param info the description of this message
 *
 * @return a new error message
 */
+ (id) errorInDocument:(NSString *)document inLine:(NSUInteger)line withTitle:(NSString*)title andInfo:(NSString *)info;

/**
 * Generator for a new warning message (a message of the type TMTWarningMessage)
 *
 * @param document the path to the latex document
 * @param line the line of the issue
 * @param title the issues title
 * @param info the description of this message
 *
 * @return a new warning message
 */
+ (id) warningInDocument:(NSString *)document inLine:(NSUInteger)line withTitle:(NSString*)title andInfo:(NSString *)info;

/**
 * Generator for a new info message (a message of the type TMTInfoMessage)
 *
 * @param document the path to the latex document
 * @param line the line of the issue
 * @param title the issues title
 * @param info the description of this message
 *
 * @return a new info message
 */
+ (id) infoInDocument:(NSString *)document inLine:(NSUInteger)line withTitle:(NSString*)title andInfo:(NSString *)info;

/**
 * Generator for a new debug message (a message of the type TMTDebugMessage)
 *
 * @param document the path to the latex document
 * @param line the line of the issue
 * @param title the issues title
 * @param info the description of this message
 *
 * @return a new debug message
 */
+ (id) debugInDocument:(NSString *)document inLine:(NSUInteger)line withTitle:(NSString*)title andInfo:(NSString *)info;

/**
 * Transform a TrackingMessageTyp to a String.
 *
 * @param type the TrackingMessageTyp to transform
 *
 * @return the type as String
 */
+ (NSString*) typeToString:(TMTTrackingMessageType)type;

/**
 * Returns a Image for a given TrackingMessageTyp.
 *
 * @param type the TrackingMessageTyp for wich a images is requested.
 *
 * @return the to the type corresponding NSImage
 */
+ (NSImage*) imageForType:(TMTTrackingMessageType)type;

/**
 * Returns the backgroundColor fo a given TrackingMessageTyp.
 *
 * @param type is the TrackingMessageTyp for which the background color is requested.
 *
 * @return the NSColor representing the background color for the given TrackingMessageTyp.
 */
+ (NSColor*) backgroundColorForType:(TMTTrackingMessageType)type;
+ (NSColor*) colorForType:(TMTTrackingMessageType)type;

/**
 * Compares to TrackingMessageTyp.
 * Compares in order by type, line, coloumn and title.
 *
 * @param other is the TrackingMessage with wich we compare.
 *
 * @return the NSComparisonResult
 */
- (NSComparisonResult)compare:(TrackingMessage*)other;
@end
